For complete series of 26 Weeks of Data Science, go to https://github.com/MayureshShilotri/26-Weeks-Of-Data-Science .

<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/26-weeks-of-data-science-banner.jpg?raw=1"/>

![Numpy+Pandas](https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/python_day3.png?raw=1)
Image source:https://blog.thedataincubator.com/2018/02/numpy-and-pandas/

# Numpy Advanced & Intro to pandas

# Program so far 
***
- Python Basics
- Python Programming Constructs
- Data Structures
- Functions
- Object Oriented Programming in Python
- NumPy
- Data Manipulation

# What are we going to learn today?
***
- NumPy: A Step Advanced
    - Indexing and Selection
    - Slicing
    - Filters
    - Replacing Values
<br/><br/>
- Pandas
    - Why Pandas ?
    - Features of Pandas
    - Pandas Data Structures
    - Pandas Series
        - How to create Series ?
        - Using index in Series

<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Concept-Alert.png?raw=1" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

# Indexing and Selection
***
Basic slicing extends Python's basic concept of slicing to N dimensions. Basic slicing occurs when obj is a `:class:` `slice` object (constructed by start:stop:step notation inside of brackets), an integer, or a tuple of slice objects and integers. :const:`Ellipsis` and :const:`newaxis` objects can be interspersed with these as well. In order to remain backward compatible with a common usage in Numeric, basic slicing is also initiated if the selection object is any non-ndarray sequence (such as a :class:`list`) containing :class:`slice` objects.

Let us look at  creating an array with numpy and indexing and selection follows from what we have learnt in python

In [1]:
# indexing one dimensional array
import numpy as np

arr = np.arange(10) #create an array of integers in range [0,10)
print("Array:", arr)

# following 2 slicing syntaxes are same as for Python List

# get the element at index 5
print("Element:", arr[5])

# get values in a range [1,9) with step of 2, thus we get all odd no.s except 9
print("Slice:", arr[1:9:2])

# try changing the values in slice to see different slices
# e.g. arr[-1:-6:-1] or arr[::-1]

Array: [0 1 2 3 4 5 6 7 8 9]
Element: 5
Slice: [1 3 5 7]


In [9]:
# indexing two dimensional array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
                 #0      #1       #2
print (arr)
print (arr[1])    # select a row
print (arr[2][0]) # [row][column]
print (arr[:,2])  # [row, column]
# in above example, we say: show all rows and show all values in column 2
print (arr[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
7
[3 6 9]
3


<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Use-Case.png?raw=1" alt="Use-Case" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

# Let's Recall our Weather Data
***
```
Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27```


### What was the wind speed recorded at 1 AM on 1st January 2012 ?

This is exactly a problem of indexing to locate information. Let us begin by reading the data and proceed how to use indexing.

[Note: The .csv file is present in the GitHub repository. To read it, we do the following--]

In [10]:
!wget "https://raw.githubusercontent.com/MayureshShilotri/26-Weeks-Of-Data-Science/master/Week-03-Numpy_advanced_Pandas_basic/data/weather_small_2012.csv"
# this will download the csv file in the Google Colab local storage which you can access directly

--2020-12-30 13:51:51--  https://raw.githubusercontent.com/MayureshShilotri/26-Weeks-Of-Data-Science/master/Week-03-Numpy_advanced_Pandas_basic/data/weather_small_2012.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 413479 (404K) [text/plain]
Saving to: ‘weather_small_2012.csv’

weather_small_2012. 100%[===================>] 403.79K  --.-KB/s    in 0.03s   

2020-12-30 13:51:51 (11.7 MB/s) - ‘weather_small_2012.csv’ saved [413479/413479]



In [11]:
%ls
# list the files stored to check whether it is downloaded
# you can also directly view in the folder through sidepanel (see folder icon on the left)

sample_data/  weather_small_2012.csv


In [12]:
# import numpy as np

weather = np.genfromtxt("./weather_small_2012.csv", dtype='|S20', skip_header=1, delimiter=",")
print(type(weather))

<class 'numpy.ndarray'>


In [13]:
# the time for which information is desired is at the second row in the data set
print(weather[1])

# wind speed is recorded in the fifth column (index 4)
print(weather[1][4])

# Alternatively
print(weather[1, 4])  # recommended and correct way of doing it

[b'2012-01-01 01:00:00' b'-1.8' b'-3.7' b'87' b'4' b'8.0' b'101.24']
b'4'
b'4'


<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Technical-Stuff.png?raw=1" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

# So What is Slicing?
***
This works very similarly to the Python list. Syntax: **`arr[start:end:step]`**

In [14]:
# Slicing one dimensional array
arr = np.arange(10)
print (arr)

print (arr[0:3])

# start from index 1 and get every 3rd elemnt
print (arr[1::3])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[1 4 7]


In [16]:
# Slicing two-dimensional array

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11,12,13,14,15]])


# 2nd row to 3rd row, 3rd column to 5th column inclusive
# remember, indexing always starts with 0
# index of first row is 0, first column is 0
print(arr[1:3, 2:4])

# notice that the output is also a 2d array

[[ 8  9]
 [13 14]]


<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Use-Case.png?raw=1" alt="Use-Case" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

### What were the temperatures, relative humidity and pressure recorded on Jan 6 ?
***
Hint: Recordings for Jan 6 are from index 120 to 143 inclusive

In [17]:
weather[120:144, [1, 3, 6]] # here we specify to display columns of index 1, 3 and 6

array([[b'-9.6', b'56', b'100.81'],
       [b'-10.0', b'55', b'100.81'],
       [b'-10.5', b'61', b'100.84'],
       [b'-10.6', b'64', b'100.76'],
       [b'-11.3', b'68', b'100.7'],
       [b'-11.8', b'71', b'100.61'],
       [b'-12.0', b'71', b'100.58'],
       [b'-14.4', b'85', b'100.52'],
       [b'-12.3', b'73', b'100.51'],
       [b'-12.5', b'71', b'100.53'],
       [b'-12.3', b'72', b'100.47'],
       [b'-12.0', b'72', b'100.36'],
       [b'-11.7', b'74', b'100.23'],
       [b'-11.9', b'74', b'100.13'],
       [b'-11.2', b'75', b'100.07'],
       [b'-11.5', b'79', b'100.06'],
       [b'-11.6', b'78', b'100.1'],
       [b'-11.2', b'78', b'100.15'],
       [b'-10.5', b'78', b'100.12'],
       [b'-10.5', b'79', b'100.13'],
       [b'-10.2', b'80', b'100.15'],
       [b'-9.5', b'79', b'100.13'],
       [b'-9.3', b'79', b'100.16'],
       [b'-9.0', b'79', b'100.15']], dtype='|S20')

<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Concept-Alert.png?raw=1" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

# Filters
***
![Filter](https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/filters1.jpg?raw=1)
Image Source:https://pixabay.com/en/yashica-filter-camera-vintage-711794/
***
Anything that takes in data, processes it, and provides an output

Input Data ⟶ Filter ⟶ Output Data

## How do I create a Filter?

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

below5_filter = (arr < 5)
print(below5_filter)

[[ True  True  True]
 [ True False False]
 [False False False]]


## Using a Filter
***
A filter can simply be used in an indexing operation (instead of numbers or slices)

In [21]:
print(arr[below5_filter])
# alternatively, you can directly specify the filter in the square brackets
# print(arr[arr>5])
# comment out the above line

[1 2 3 4]
[6 7 8 9]


<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Use-Case.png?raw=1" alt="Use-Case" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

### What were the date/times when the temperature was above 32 degrees and visibility over 30 km ?


In [26]:
# select the date time column
times = weather[:,0] #all rows, first column

# create filter: temperature over 32 degrees
temperature_over_32 = weather[:,1].astype(np.float16) > 32
# astype(np.float16) is a function used to convert the string data type temporarily to float

# create filter: visibility above 30 km
visibility_over_30 = weather[:,-2].astype(np.float16) > 30

# get the times
times[temperature_over_32 & visibility_over_30] 
# "&" is bitwise AND operator, which means it ANDs each pair of values in both filter arrays

array([b'2012-07-13 14:00:00', b'2012-07-14 14:00:00',
       b'2012-07-14 15:00:00', b'2012-07-14 16:00:00',
       b'2012-07-14 17:00:00'], dtype='|S20')

<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Technical-Stuff.png?raw=1" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

# Replacing values
***
We can also use comparisons to replace values in an array, based on certain conditions. The code to do the same is as shown below. The code to replacing values on certain conditions is as follows.

In [27]:
# Replacing Values
# import numpy as np

vector = np.array([5, 10, 15, 20])
print (vector)

equal_to_ten_or_five = (vector == 10) | (vector == 5)
vector[equal_to_ten_or_five] = 50

print (vector)

[ 5 10 15 20]
[50 50 15 20]


<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/ppt-icons.png?raw=1" alt="Use-Case" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

### Mini Challenge - 1
***
Can you locate the number 5 in the array arr

In [32]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.where(arr==5))

(array([1]), array([1]))


<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Use-Case.png?raw=1" alt="Use-Case" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

### Mini Challenge - 2
***
Now its your turn again. Can you print the first 2 rows and first 3 columns of the array `arr`.

In [ ]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11,12,13,14,15]])


In [33]:
print(arr[:2,:3])

[[1 2 3]
 [4 5 6]]


<h1 align='center'>Help us spread the word for 26-Weeks-Of-Data-Science.</h1>
***
![team](../images/team_resized.jpeg)<br/>
We wish to ensure that maximum learners reap the benefits of our study-plan. Please like, share the post below & help us share
<br/><br/>
<div style="text-align: center"><a href="https://www.linkedin.com/feed/update/urn:li:activity:6487273029977112576/"  class="btn-hover color-3" style="text-align: center;background-color: #543d98;padding: 12px 15px;color: #fff!important;border: 0;border-radius: 4px;box-shadow: 2px 2px 2px #999; font-weight: bold;">HIT HERE TO HELP US SHARE</a></div><br>

# Introduction to
***
![Pandas_logo](https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/pandas.png?raw=1)
Image source:https://en.wikipedia.org/wiki/Pandas_(software)
***
The most widely used Python library for data science

It has nothing to do with cute bears. Instead it stands for **Pan**el **da**ta - **Pandas**
***
![cute_pandas](https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/cute_pandas.jpg?raw=1)
Image source:https://wallpaper-house.com/wallpaper-id-399850.php

<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Concept-Alert.png?raw=1" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

## Why Pandas ?
***
<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/why-pandas.jpg?raw=1" width="70%"/>

<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Concept-Alert.png?raw=1" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

## Features of Pandas
***
<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/pandas-features.jpg?raw=1" width="70%"/>

<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Concept-Alert.png?raw=1" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

# Pandas Data Structures
***
<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/pandas-datastructures.jpg?raw=1" width="70%"/>

<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Concept-Alert.png?raw=1" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

# Pandas Series
***
* Very similar to a NumPy array.

* What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location.

<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Technical-Stuff.png?raw=1" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

## How to create a Series?
***
You can convert a list, numpy array, or dictionary to a Series. To create a series you call the function pd.Series(). Let's see an example of the same.

We will create a series from 
- list
- numpy array 
- dictionary

In [34]:
#creating a pandas series from a list
import pandas as pd

my_list = [10, 20, 30]
series = pd.Series(my_list)

print(series)
print(series.index)
print(series.values)

0    10
1    20
2    30
dtype: int64
RangeIndex(start=0, stop=3, step=1)
[10 20 30]


In [35]:
# creating a series from numPy Array
# import numpy as np
# import pandas as pd

index = ['a','b','c']
arr = np.array([10,20,30])

pd.Series(data=my_list,index=index)

a    10
b    20
c    30
dtype: int64

In [36]:
# creating a series from dictionary
# import pandas as pd

d = {'a':10, 'b':20, 'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Concept-Alert.png?raw=1" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

## Using Index in a Series
***
* The key to using a Series is understanding its index.

* Pandas makes use of these index names or numbers by allowing for **fast lookups** of information (works like a hash table or dictionary).


In [38]:
# Custom index
# import pandas as pd
ser1 = pd.Series([1,2,3,4], index=['USA', 'Germany','USSR', 'Japan']) 
ser2 = pd.Series([1,2,5,4], index=['USA', 'Germany','Italy', 'Japan'])   

# get the value of 'USA'
print(ser1['USA'])
print(ser1[1])

1
2


In [39]:
print(ser1 + ser2)
# this fills NaN i.e. Not a number in the fields which are not present in both

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64


In [41]:
print(ser1.add(ser2, fill_value=0))
# this adds all values, fills 0 for wherever the field is not present

Germany    4.0
Italy      5.0
Japan      8.0
USA        2.0
USSR       3.0
dtype: float64


<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Use-Case.png?raw=1" alt="Use-Case" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

### Question: What were the pressure values recorded on Jan 6 ?
***
Last time we did this, we knew that the recordings for Jan 6 were from index 120 to 143 inclusive.
The solution was:

    weather[120:144, 6]

Can we do it without that knowledge (of indices) this time?

<div class="alert alert-block alert-success">**Solution 1: What were the first 5 pressure values recorded on Jan 6 ?**</div>


In [43]:
# import pandas as pd

index = weather[:, 0]
pressure_values = weather[:, -1].astype(np.float16)
weather_series = pd.Series(pressure_values, index)
indices = ['2012-01-06 {:02d}:00:00'.format(i) for i in range(5)]
indices = [i.encode() for i in indices]
print(indices)

print('-' * 40)

jan6_pressures = [weather_series[ind] for ind in indices]
print(jan6_pressures)

[b'2012-01-06 00:00:00', b'2012-01-06 01:00:00', b'2012-01-06 02:00:00', b'2012-01-06 03:00:00', b'2012-01-06 04:00:00']
----------------------------------------
[100.8, 100.8, 100.8, 100.75, 100.7]


<div class="alert alert-block alert-success">**Solution 2: What were the first 5 pressure values recorded on Jan 6 ?**</div>


***
Surely there must be a better way than using loops and falling back to Python lists?

In [44]:
index = weather[:, 0]
pressure_values = weather[:, -1].astype(np.float16)
weather_series = pd.Series(pressure_values, index)
weather_series.index = [i.decode() for i in weather_series.index]
weather_series.index
jan6_filter = weather_series.index.str.startswith('2012-01-06')
print(jan6_filter)

print('-' * 40)

jan6_pressures = weather_series[jan6_filter]
print(jan6_pressures[:5])

[False False False ... False False False]
----------------------------------------
2012-01-06 00:00:00    100.8125
2012-01-06 01:00:00    100.8125
2012-01-06 02:00:00    100.8125
2012-01-06 03:00:00    100.7500
2012-01-06 04:00:00    100.6875
dtype: float16


<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Use-Case.png?raw=1" alt="Use-Case" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

## Mini Challenge - 3
***
Can you find the value of 'USSR' from the series ser1

In [45]:
# import pandas as pd
ser1 = pd.Series([1,2,3,4], index=['USA', 'Germany','USSR', 'Japan']) 
ser2 = pd.Series([1,2,5,4], index=['USA', 'Germany','Italy', 'Japan'])   
print(ser1['USSR'])

3


<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Use-Case.png?raw=1" alt="Use-Case" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

## Mini Challenge - 4
***
Normalize the data by creating a function to perform following steps:

-Find sum of all values in a series

-Divide all values by the calculated sum

-Return the new series

Use the above function for ser1, ser2

Add both Series using Series.add(ser, fill_value=0).
Divide the answer by 2.

Thus, the sum of all values for your answer series must be 1.

In [52]:
def myNormalizer(ser):
  mySum = sum(ser)
  print(mySum)
  if mySum!=0:
    mySer = ser.div(mySum)
  return mySer

newSer1 = myNormalizer(ser1)
newSer2 = myNormalizer(ser2)
ans = newSer1.add(newSer2, fill_value=0).div(2)
print(ans)
print(sum(ans))

10
12
Germany    0.366667
Italy      0.416667
Japan      0.733333
USA        0.183333
USSR       0.300000
dtype: float64
2.0


# Further Reading
***
- NumPy documentation: http://www.numpy.org/
- Pandas documentation: http://pandas.pydata.org/


<img src="https://github.com/mockingmoon/26-Weeks-Of-Data-Science/blob/master/Week-03-Numpy_advanced_Pandas_basic/images/icon/Recap.png?raw=1" alt="Recap" style="width: 100px;float:left; margin-right:15px"/>
<br />

# In-session Recap Time
***
- Indexing and Selection
- Slicing
- Filters
- Replacing Values
* Pandas
    * Data Structures in Pandas
    * Features of Pandas
    * Series

# Thank You
***
### Coming up next...
***
- Pandas Advanced: DataFrame
- Visualizing data

For more queries - Reach out to academics@greyatom.com 